development:
  auth0_client_id: P1ExlWvgX59OJzdCVcyfQbbxZEFZYK2H
  auth0_client_secret: BPaqu1OS_ATxzTZ82LVDvRoVa7uI1HDeglgnbmHporKfat_yfVHj0f4ZRXhaRJ2T
  auth0_domain: atulub.us.auth0.com

test:
  auth0_client_id: P1ExlWvgX59OJzdCVcyfQbbxZEFZYK2H
  auth0_client_secret: BPaqu1OS_ATxzTZ82LVDvRoVa7uI1HDeglgnbmHporKfat_yfVHj0f4ZRXhaRJ2T
  auth0_domain: atulub.us.auth0.com

production:
  auth0_client_id: P1ExlWvgX59OJzdCVcyfQbbxZEFZYK2H
  auth0_client_secret: BPaqu1OS_ATxzTZ82LVDvRoVa7uI1HDeglgnbmHporKfat_yfVHj0f4ZRXhaRJ2T
  auth0_domain: atulub.us.auth0.com